Fix setPinInterrupt & new features
TD-er/SC16IS752 pull request #2
Opened 2021-02-16 19:42 UTC by szerwi

Changes that I have made:
* Changed all "WIRE" to "Wire" and removed creating WIRE object at the beginning of .cpp. Thanks to this, it is possible to use I2C on custom pins on ESP32. If it destroys any other functionality, it is worth to consider passing Wire object in constructor / begin method.
* Changed ```SetPinInterrupt();``` function so it is possible to enable or disable interrupt on specific pin
* Added ```GetPinInterrupt()``` function
* Added ```readBytes()``` function
* Added ```readStringUntil()``` function

2021-02-16 21:00 UTC, TD-er requested changes

2021-02-16 21:00 UTC, TD-er commented on SC16IS752.cpp
> -#elif ESP8266 // ESP8266
Why not change this into something like this:
```c++
#elif defined(ESP8266) || defined(ESP32}
```
Then it is later easier to change it to other I2C implementations as well.

2021-02-16 21:00 UTC, TD-er commented on SC16IS752.cpp
> +   }
Please make the indentation a bit more uniform.
It wasn't great, but since someone is now working on it, better make it a bit less tingling on the OCD senses :)

2021-02-16 21:26 UTC, szerwi commented on SC16IS752.cpp
> -#elif ESP8266 // ESP8266
Changed

2021-02-16 21:26 UTC, szerwi commented on SC16IS752.cpp
> +   }
Changed ;)

2021-02-16 22:37 UTC, TD-er commented
Maybe also update the `library.properties` and `library.json` file to be a higher version number (1.0.2 for example)
When merging it, I will add a new tag too, so PIO will recognize different versions.

2021-02-16 22:51 UTC, szerwi commented
Done

2021-02-16 22:56 UTC, TD-er commented
Looking good.
I will have a new closer look at it tomorrow.

2021-02-24 17:56 UTC, szerwi commented
@TD-er Have you reviewed it? Do you have any other change requests before merging?

2021-02-26 10:37 UTC, TD-er commented
Not yet, hopefully I will have time this evening.

2021-05-31 14:57 UTC, edouardreg commented
Hello, is it possible to write/read strings to serial channels with this library ? Because Szervi told "Added readStringUntil() function" but can't see it in the .cpp or .h files ?
Thanks.

2021-05-31 15:12 UTC, szerwi commented
@edouardreg my PR was not merged yet. It seems like you should be able to write string using `write(uint8_t channel, const uint8_t * buffer, size_t size)` function. I think you should be able to read string using `readBytes(uint8_t channel, uint8_t *buffer, size_t length)`. But for now there is no `readStringUntil()` function in master that I've implemented.

2021-06-01 14:11 UTC, edouardreg commented
Thanks for your reply, I'll test it soon.

2022-12-08 08:54 UTC, merged

2022-12-08 08:55 UTC, TD-er commented
Sorry I had forgotten about this PR...